import Foundation
import Metal
import simd
import UntoldEngine

/// Stable IDs shared by plugin registration, graph declarations, and shaders.
///
/// IDs occupy engine-wide registries, so a production provider should namespace
/// every value with a reverse-domain or similarly unique package prefix.
public enum WaterRenderPluginContract {
    public static let pluginID = "com.untold.fixture.water"
    public static let extensionID = "com.untold.fixture.water.surface"
    public static let shaderLibraryID: RenderShaderLibraryID = "com.untold.fixture.water.shaders"
    public static let computePipelineID: ComputePipelineType = "com.untold.fixture.water.generate"
    public static let surfacePipelineID: RenderPipelineType = "com.untold.fixture.water.surface"
    public static let proceduralPipelineID: RenderPipelineType = "com.untold.fixture.water.procedural"
    public static let argumentLayoutID = "com.untold.fixture.water.surface.arguments"
    public static let colorTextureID: RenderTextureResourceID = "com.untold.fixture.water.color"
    public static let normalTextureID: RenderTextureResourceID = "com.untold.fixture.water.normal"
}

/// Package-level manifest and factory for all Rendering Extensions in this module.
///
/// A plugin is the distribution and lifecycle wrapper. The rendering work still
/// lives in ordinary `RenderExtension` implementations returned by
/// `makeRenderExtensions()`.
public struct WaterRenderPlugin: RenderExtensionPlugin {
    /// Locates the precompiled shader library bundled by this Swift package.
    ///
    /// `Bundle.module` is generated by SwiftPM and is accessible only from code
    /// inside this package target. Applications should not try to access it.
    public static var bundledMetallibURL: URL? {
        Bundle.module.url(forResource: "WaterRenderPlugin", withExtension: "metallib")
    }

    /// Identity and compatibility metadata validated before installation.
    public let manifest = RenderExtensionPluginManifest(
        id: WaterRenderPluginContract.pluginID,
        displayName: "Water Render Plugin Fixture",
        version: RenderExtensionPluginVersion(major: 1, minor: 0, patch: 0)
    )

    /// Creates the package plugin. Registration occurs only when it is installed.
    public init() {}

    /// Creates every extension owned by this plugin installation.
    ///
    /// Installation is atomic: if any returned extension fails registration,
    /// the engine rolls back the complete plugin instead of leaving a partial set.
    public func makeRenderExtensions() -> [any RenderExtension] {
        [WaterSurfaceRenderExtension(shaderBundle: .module)]
    }
}

/// Installs every Rendering Extension supplied by this package.
///
/// The consuming application imports `WaterRenderPlugin` and calls this function
/// before renderer creation. Inspect the returned result to handle manifest,
/// shader, pipeline, resource, or graph registration failures.
@discardableResult
public func registerWaterRenderPlugin() -> RenderExtensionPluginInstallationResult {
    RenderExtensionPluginRegistry.shared.install(WaterRenderPlugin())
}

/// Opt-in component identifying entities rendered by the water surface pass.
///
/// Public components let the consuming application configure package-owned
/// rendering behavior without exposing the extension's internal implementation.
public final class WaterSurfaceComponent: Component, @unchecked Sendable {
    public var tint = SIMD4<Float>(0.10, 0.45, 0.65, 1.0)
    public var roughness: Float = 0.08
    public var waveStrength: Float = 0.18

    public required init() {}
}

/// CPU representation of the argument-buffer value read by the fragment shader.
/// Its field order and alignment must match `WaterSurfaceUniforms` in Metal.
private struct WaterSurfaceUniforms {
    var tint: SIMD4<Float>
    var roughness: Float
    var waveStrength: Float
    var padding0: Float = 0
    var padding1: Float = 0
}

/// Rendering implementation installed by `WaterRenderPlugin`.
///
/// The extension follows the same mental model as an application-local extension:
///
/// 1. Register its bundled shader library.
/// 2. Declare owned textures and their lifecycle.
/// 3. Declare argument-buffer members shared by Swift and Metal.
/// 4. Register compute and model-surface pipelines.
/// 5. Add graph passes with complete resource access declarations.
///
/// Only `id` and `buildGraph` are required by `RenderExtension`. This example
/// implements every optional hook because it demonstrates the complete package.
public final class WaterSurfaceRenderExtension: RenderExtension, @unchecked Sendable {
    /// Stable owner ID used for collision detection, diagnostics, and cleanup.
    public let id = WaterRenderPluginContract.extensionID

    private let shaderBundle: Bundle
    private let generatePassID = "com.untold.fixture.water.generate-pass"
    private let surfacePassID = "com.untold.fixture.water.surface-pass"
    private let proceduralPassID = "com.untold.fixture.water.procedural-pass"

    /// Creates the extension with the bundle containing its precompiled metallib.
    ///
    /// The plugin factory passes `.module`; accepting a bundle keeps the rendering
    /// implementation testable and reusable from another bundle if necessary.
    public init(shaderBundle: Bundle) {
        self.shaderBundle = shaderBundle
    }

    /// Registers the package metallib containing the compute and fragment functions.
    public func registerShaderLibraries(_ registry: RenderShaderLibraryRegistry) {
        registry.registerLibrary(
            WaterRenderPluginContract.shaderLibraryID,
            bundle: shaderBundle,
            resource: "WaterRenderPlugin"
        )
    }

    /// Declares textures owned exclusively by this extension.
    ///
    /// Every pass using these textures must repeat the corresponding read or write
    /// access in `buildGraph`; registration alone does not grant pass access.
    public func registerResources(_ registry: RenderResourceRegistry) {
        registry.registerTexture(
            RenderExtensionTextureDescriptor(
                id: WaterRenderPluginContract.colorTextureID,
                label: "Fixture Water Color",
                size: .viewportScale(1),
                pixelFormat: .rgba16Float,
                usage: [.shaderRead, .shaderWrite]
            )
        )
        registry.registerTexture(
            RenderExtensionTextureDescriptor(
                id: WaterRenderPluginContract.normalTextureID,
                label: "Fixture Water Normal",
                size: .viewportScale(1),
                pixelFormat: .rgba16Float,
                usage: [.shaderRead, .shaderWrite]
            )
        )
    }

    /// Declares the local texture and buffer IDs encoded for each surface draw.
    ///
    /// These IDs must match the members read from
    /// `UntoldModelSurfaceExtensionArguments` in the Metal fragment function.
    public func registerArgumentBuffers(_ registry: RenderExtensionArgumentBufferRegistry) {
        registry.registerArgumentBuffer(
            RenderExtensionArgumentBufferDescriptor(
                id: WaterRenderPluginContract.argumentLayoutID,
                textures: [
                    RenderExtensionArgumentTexture(
                        id: RenderExtensionModelSurfaceArgument.texture0
                    ),
                    RenderExtensionArgumentTexture(
                        id: RenderExtensionModelSurfaceArgument.texture1
                    ),
                ],
                buffers: [
                    RenderExtensionArgumentBuffer(
                        id: RenderExtensionModelSurfaceArgument.buffer0
                    ),
                ]
            )
        )
    }

    /// Creates the compute pipeline that generates the extension textures.
    public func registerComputePipelines(_ registry: ComputePipelineRegistry) {
        registry.registerComputePipeline(
            RenderExtensionComputePipelineDescriptor(
                id: WaterRenderPluginContract.computePipelineID,
                function: "waterFixtureTextureKernel",
                shaderLibrary: .registered(WaterRenderPluginContract.shaderLibraryID),
                name: "Fixture Water Texture"
            )
        )
    }

    /// Creates the model-surface pipeline using the engine vertex stage and the
    /// package's argument-buffer fragment function.
    public func registerPipelines(_ registry: RenderPipelineRegistry) {
        registry.registerModelSurfacePipeline(
            WaterRenderPluginContract.surfacePipelineID,
            fragmentShader: "waterFixtureSurfaceFragment",
            fragmentShaderLibrary: .registered(WaterRenderPluginContract.shaderLibraryID),
            name: "Fixture Water Surface",
            validation: .warn(argumentLayoutID: WaterRenderPluginContract.argumentLayoutID)
        )
        registry.registerScenePipeline(
            WaterRenderPluginContract.proceduralPipelineID,
            vertexShader: "waterFixtureProceduralVertex",
            fragmentShader: "waterFixtureProceduralFragment",
            vertexShaderLibrary: .registered(WaterRenderPluginContract.shaderLibraryID),
            fragmentShaderLibrary: .registered(WaterRenderPluginContract.shaderLibraryID),
            depthCompareFunction: .lessEqual,
            depthEnabled: true,
            reverseZCompatible: true,
            blendMode: .alphaPremultiplied,
            name: "Fixture Procedural Geometry"
        )
    }

    /// Adds generation and drawing work to the render graph.
    ///
    /// `buildGraph` declares work only. The closures execute later while encoding
    /// a frame. Both passes use the same stable stage, and registration order plus
    /// the declared write/read hazard orders generation before drawing.
    public func buildGraph(
        _ builder: inout RenderGraphBuilder,
        context _: RenderGraphBuildContext
    ) {
        builder.addPass(
            id: generatePassID,
            stage: .beforePostProcess,
            resources: [
                .texture(WaterRenderPluginContract.colorTextureID, access: .write),
                .texture(WaterRenderPluginContract.normalTextureID, access: .write),
            ]
        ) { context in
            // Resource and pipeline lookups are scoped to declarations made by
            // this extension and this pass. A missing value safely skips encoding.
            guard let colorTexture = context.resources.texture(
                WaterRenderPluginContract.colorTextureID
            ), let normalTexture = context.resources.texture(
                WaterRenderPluginContract.normalTextureID
            ), let pipeline = context.computePipelines.pipeline(
                WaterRenderPluginContract.computePipelineID
            )?.pipelineState, let encoder = context.commandBuffer.makeComputeCommandEncoder() else {
                return
            }

            encoder.setComputePipelineState(pipeline)
            encoder.setTexture(colorTexture, index: 0)
            encoder.setTexture(normalTexture, index: 1)
            let width = max(1, pipeline.threadExecutionWidth)
            let height = max(1, pipeline.maxTotalThreadsPerThreadgroup / width)
            encoder.dispatchThreads(
                MTLSize(width: colorTexture.width, height: colorTexture.height, depth: 1),
                threadsPerThreadgroup: MTLSize(width: width, height: height, depth: 1)
            )
            encoder.endEncoding()
        }

        builder.addPass(
            id: surfacePassID,
            stage: .beforePostProcess,
            resources: [
                .texture(WaterRenderPluginContract.colorTextureID, access: .read),
                .texture(WaterRenderPluginContract.normalTextureID, access: .read),
            ]
        ) { context in
            // The helper supplies engine model bindings and draws only entities
            // carrying WaterSurfaceComponent.
            context.drawModelSurfaceEntities(
                pipeline: WaterRenderPluginContract.surfacePipelineID,
                matching: [WaterSurfaceComponent.self],
                label: "Fixture Water Surface",
                argumentLayoutID: WaterRenderPluginContract.argumentLayoutID,
                bindArguments: { arguments, entityID, resources in
                    // This closure runs once per matching entity, allowing each
                    // model to encode independent component values.
                    guard let component = getEntityComponent(
                        entityId: entityID,
                        componentType: WaterSurfaceComponent.self
                    ) else {
                        return
                    }

                    arguments.setTexture(
                        resources.texture(WaterRenderPluginContract.colorTextureID),
                        id: RenderExtensionModelSurfaceArgument.texture0
                    )
                    arguments.setTexture(
                        resources.texture(WaterRenderPluginContract.normalTextureID),
                        id: RenderExtensionModelSurfaceArgument.texture1
                    )
                    var uniforms = WaterSurfaceUniforms(
                        tint: component.tint,
                        roughness: component.roughness,
                        waveStrength: component.waveStrength
                    )
                    arguments.setBytes(
                        &uniforms,
                        id: RenderExtensionModelSurfaceArgument.buffer0
                    )
                }
            )
        }

        builder.addPass(
            id: proceduralPassID,
            stage: .beforePostProcess
        ) { context in
            guard let pipeline = context.renderPipelines.pipeline(
                WaterRenderPluginContract.proceduralPipelineID
            ), let pipelineState = pipeline.pipelineState,
            let encoder = context.sceneRenderTargets.makeRenderCommandEncoder(
                actions: .loadAndStore,
                label: "Fixture Procedural Geometry"
            )
            else {
                return
            }
            defer { encoder.endEncoding() }

            var viewProjection = context.camera.viewProjectionMatrix
            encoder.setRenderPipelineState(pipelineState)
            if let depthState = pipeline.depthState {
                encoder.setDepthStencilState(depthState)
            }
            encoder.setVertexBytes(
                &viewProjection,
                length: MemoryLayout<simd_float4x4>.stride,
                index: 0
            )
            encoder.drawPrimitives(type: .triangle, vertexStart: 0, vertexCount: 3)
        }
    }
}
