//
//  BuildTemplates.swift
//  UntoldEngine
//
//  Embedded build templates for production distribution
//  These are used as fallback when file-based templates aren't available
//

import Foundation

enum BuildTemplates {
    // MARK: - Package.swift Template

    static let packageSwift = """
    // swift-tools-version: 6.0
    // The swift-tools-version declares the minimum version of Swift required to build this package.

    import PackageDescription

    let package = Package(
        name: "{{PROJECT_NAME}}",
        platforms: [
            .macOS(.v{{MACOS_VERSION}})
        ],
        products: [
            .executable(
                name: "{{PROJECT_NAME}}",
                targets: ["{{PROJECT_NAME}}"]
            ),
        ],
        dependencies: [
            // UntoldEngine from GitHub
            .package(url: "https://github.com/untoldengine/UntoldEngine.git", branch: "develop")
        ],
        targets: [
            .executableTarget(
                name: "{{PROJECT_NAME}}",
                dependencies: [
                    .product(name: "UntoldEngine", package: "UntoldEngine")
                ],
                resources: [
                    .process("GameData")
                ],
                swiftSettings: [
                    .swiftLanguageMode(.v5)
                ]
            ),
        ]
    )
    """

    // MARK: - main.swift Template

    static let mainSwift = """
    //
    //  main.swift
    //  {{PROJECT_NAME}}
    //
    //  Generated by UntoldEngine Build System
    //

    #if os(macOS)
        import MetalKit
        import SwiftUI
        import UntoldEngine

        // GameScene: Initialize your game and write game-specific logic
        class GameScene {
            private var sceneLoaded = false
            private var sceneURL: URL?

            init() {
                // Set asset base path to bundled GameData directory
                // Try multiple approaches to find GameData
                if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
                    assetBasePath = gameDataURL
                    Logger.log(message: "✅ Found GameData at: \\(gameDataURL.path)")
                } else if let resourceURL = Bundle.main.resourceURL {
                    // Fallback: Look for GameData in Resources
                    let gameDataPath = resourceURL.appendingPathComponent("GameData")
                    if FileManager.default.fileExists(atPath: gameDataPath.path) {
                        assetBasePath = gameDataPath
                        Logger.log(message: "✅ Found GameData in Resources: \\(gameDataPath.path)")
                    } else {
                        Logger.log(message: "⚠️ GameData not found. Bundle resources: \\(resourceURL.path)")
                    }
                }

                // Find the scene file but DON'T load it yet
                findBundledScene()

                // Load USC scripts from GameData/Scripts
                loadBundledScripts()

                // Initialize game systems for play mode
                gameMode = true
                AnimationSystem.shared.isEnabled = true
                USCSystem.shared.startPlayMode() 
            }

            /// Find the first scene in GameData/Scenes (deferred loading)
            private func findBundledScene() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    Logger.log(message: "⚠️ GameData directory not found")
                    return
                }

                let scenesURL = gameDataURL.appendingPathComponent("Scenes")

                guard let sceneFiles = try? FileManager.default.contentsOfDirectory(
                    at: scenesURL,
                    includingPropertiesForKeys: nil
                ), let firstScene = sceneFiles.first(where: { $0.pathExtension == "json" }) else {
                    Logger.log(message: "⚠️ No scene files found")
                    return
                }

                // Store the scene URL for deferred loading
                sceneURL = firstScene
                Logger.log(message: "📋 Found scene: \\(firstScene.lastPathComponent) (will load on first frame)")
            }

            /// Load all USC scripts from GameData/Scripts
            private func loadBundledScripts() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    return
                }

                let scriptsURL = gameDataURL.appendingPathComponent("Scripts")

                // Use the new loadScripts() function
                let count = loadScripts(from: scriptsURL)
                Logger.log(message: "✅ Loaded \\(count) script(s) from bundle")
            }

            /// Check if renderer resources are ready for scene loading
            private func isRendererReady() -> Bool {
                // Check viewport is valid (ensures initSizeableResources has run)
                return renderInfo.viewPort.x > 0 && renderInfo.viewPort.y > 0
            }

            /// Called every frame - add custom game logic here
            func update(deltaTime _: Float) {
                // Deferred scene loading: load on the first frame when renderer is fully initialized
                if !sceneLoaded, let url = sceneURL {
                    // Only load scene when renderer is confirmed ready
                    if isRendererReady() {
                        playSceneAt(url: url)
                        sceneLoaded = true
                        Logger.log(message: "✅ Scene loaded and playing: \\(url.lastPathComponent)")
                    } else {
                        // Renderer not ready yet, will try again next frame
                        return
                    }
                }

                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom update logic here
            }

            /// Called for input handling - add custom input logic here
            func handleInput() {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom input handling here
            }
        }

        // AppDelegate: Boilerplate code - Handles window, renderer, and GameScene initialization
        class AppDelegate: NSObject, NSApplicationDelegate {
            var window: NSWindow!
            var renderer: UntoldRenderer!
            var gameScene: GameScene!

            func applicationDidFinishLaunching(_: Notification) {
                print("🎮 Launching {{PROJECT_NAME}}")

                // Step 1. Create and configure the window
                window = NSWindow(
                    contentRect: NSRect(x: 0, y: 0, width: 1920, height: 1080),
                    styleMask: [.titled, .closable, .resizable],
                    backing: .buffered,
                    defer: false
                )

                window.title = "{{PROJECT_NAME}}"
                window.center()

                // Step 2. Initialize the renderer and connect metal content
                guard let renderer = UntoldRenderer.create() else {
                    print("❌ Failed to initialize the renderer.")
                    return
                }

                window.contentView = renderer.metalView
                self.renderer = renderer

                // Step 3. Create the game scene and connect callbacks
                gameScene = GameScene()
                renderer.setupCallbacks(
                    gameUpdate: { [weak self] deltaTime in self?.gameScene.update(deltaTime: deltaTime) },
                    handleInput: { [weak self] in self?.gameScene.handleInput() }
                )

                window.makeKeyAndOrderFront(nil)
                NSApp.setActivationPolicy(.regular)
                NSApp.activate(ignoringOtherApps: true)
            }

            func applicationShouldTerminateAfterLastWindowClosed(_: NSApplication) -> Bool {
                true
            }
        }

        // Entry point
        let app = NSApplication.shared
        let delegate = AppDelegate()
        app.delegate = delegate
        app.run()
    #endif
    """

    // MARK: - GameScene.swift Template (optional separate file)

    // Note: GameScene is included in main.swift by default
    // This is provided as reference if developers want to split it out

    static let gameSceneSwift = """
    //
    //  GameRuntime.swift
    //  {{PROJECT_NAME}}
    //
    //  Game runtime that loads and executes game data
    //  Generated by UntoldEngine Build System
    //

    import Foundation
    import UntoldEngine

    /// Lightweight runtime wrapper that loads bundled game data and starts the engine
    class GameRuntime {

        private var loadedScenes: [Scene] = []
        private var loadedScripts: [USCScript] = []

        init() {
            Logger.log(message: "🎮 {{PROJECT_NAME}} Runtime Initialized")
        }

        /// Load all game data from the bundle
        func loadGameData() {
            Logger.log(message: "📦 Loading game data...")

            // Load scenes
            loadScenes()

            // Load USC scripts
            loadScripts()

            // Initialize scripting system
            initScriptingSystem()

            Logger.log(message: "✅ Game data loaded successfully")
        }

        /// Start the game
        func run() {
            Logger.log(message: "🚀 Starting {{PROJECT_NAME}}...")

            // Initialize the engine with first scene
            if let firstScene = loadedScenes.first {
                initEngine(scene: firstScene)
            } else {
                Logger.log(message: "⚠️ No scenes found, creating default scene")
                initEngine(scene: createDefaultScene())
            }

            // Start the main loop
            startGameLoop()
        }

        // MARK: - Private Helpers

        private func loadScenes() {
            guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                Logger.log(message: "⚠️ GameData directory not found")
                return
            }

            let scenesURL = gameDataURL.appendingPathComponent("Scenes")

            guard let sceneFiles = try? FileManager.default.contentsOfDirectory(
                at: scenesURL,
                includingPropertiesForKeys: nil
            ) else {
                Logger.log(message: "⚠️ No scenes directory found")
                return
            }

            for sceneFile in sceneFiles where sceneFile.pathExtension == "json" {
                if let scene = loadScene(from: sceneFile) {
                    loadedScenes.append(scene)
                    Logger.log(message: "📄 Loaded scene: \\(scene.name)")
                }
            }
        }

        private func loadScene(from url: URL) -> Scene? {
            guard let data = try? Data(contentsOf: url),
                  let scene = try? JSONDecoder().decode(Scene.self, from: data) else {
                Logger.log(message: "❌ Failed to load scene from \\(url.lastPathComponent)")
                return nil
            }
            return scene
        }

        private func loadScripts() {
            guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                return
            }

            let scriptsURL = gameDataURL.appendingPathComponent("Scripts")

            guard let scriptFiles = try? FileManager.default.contentsOfDirectory(
                at: scriptsURL,
                includingPropertiesForKeys: nil
            ) else {
                Logger.log(message: "⚠️ No scripts directory found")
                return
            }

            for scriptFile in scriptFiles where scriptFile.pathExtension == "uscript" {
                if let script = loadUSCScript(from: scriptFile) {
                    loadedScripts.append(script)
                    Logger.log(message: "📜 Loaded script: \\(script.name)")
                }
            }
        }

        private func createDefaultScene() -> Scene {
            let scene = createScene(named: "DefaultScene")
            Logger.log(message: "🎬 Created default scene")
            return scene
        }

        private func startGameLoop() {
            // The engine's main loop will take over from here
            Logger.log(message: "🔄 Game loop started")
        }
    }
    """

    // MARK: - README.md Template

    static let readmeMd = """
    # {{PROJECT_NAME}}

    Generated by **UntoldEngine Build System**

    ## 🎮 About

    This is a macOS game project built with UntoldEngine. The project includes all your game data (scenes, scripts, assets) bundled and ready to run.

    ## 🚀 Quick Start

    ### Build and Run

    ```bash
    swift build
    swift run
    ```

    ### Open in Xcode

    ```bash
    open Package.swift
    ```

    Then press `Cmd+R` to build and run.

    ## 📁 Project Structure

    ```
    {{PROJECT_NAME}}/
    ├── Package.swift              # Swift Package configuration
    ├── README.md              
    └── Sources/
        └── {{PROJECT_NAME}}/
            ├── main.swift         # Entry point
            ├── GameRuntime.swift  # Game loader
            └── GameData/          # Bundled game content
                ├── Scenes/        # Scene files (.json)
                ├── Scripts/       # USC scripts (.uscript)
                ├── Models/        # 3D models
                ├── Textures/      # Texture files
                └── Shaders/       # Compiled Metal shaders
    ```

    ## 🎯 Requirements

    - macOS {{MACOS_VERSION}} or later
    - Xcode 15.0 or later
    - Swift 5.9 or later

    ## 📝 Notes

    - This project uses UntoldEngine as a Swift Package dependency from GitHub
    - All game data is bundled as resources
    - USC scripts are loaded and executed at runtime

    ## 🔗 UntoldEngine

    Powered by [UntoldEngine](https://github.com/untoldengine/UntoldEngine)

    ---

    Built with ❤️ using UntoldEngine
    """

    // MARK: - Helper Methods

    /// Get all template files for a target
    static func getTemplateFiles(for _: BuildTarget) -> [String: String] {
        [
            "Package.swift": packageSwift,
            "README.md": readmeMd,
            "Sources/{{PROJECT_NAME}}/main.swift": mainSwift,
        ]
    }
}
