//
//  BuildTemplates.swift
//  UntoldEngine
//
//  Embedded build templates for production distribution
//  These are used as fallback when file-based templates aren't available
//

import Foundation

#if os(macOS)

    enum BuildTemplates {
        // MARK: - Package.swift Template

        static let packageSwift = """
        // swift-tools-version: 6.0
        // The swift-tools-version declares the minimum version of Swift required to build this package.

        import PackageDescription

        let package = Package(
            name: "{{PROJECT_NAME}}",
            platforms: [
                .macOS(.v{{MACOS_VERSION}})
            ],
            products: [
                .executable(
                    name: "{{PROJECT_NAME}}",
                    targets: ["{{PROJECT_NAME}}"]
                ),
            ],
            dependencies: [
                // UntoldEngine from GitHub
                .package(url: "https://github.com/untoldengine/UntoldEngine.git", branch: "develop")
            ],
            targets: [
                .executableTarget(
                    name: "{{PROJECT_NAME}}",
                    dependencies: [
                        .product(name: "UntoldEngine", package: "UntoldEngine")
                    ],
                    resources: [
                        .process("GameData")
                    ],
                    swiftSettings: [
                        .swiftLanguageMode(.v5)
                    ]
                ),
            ]
        )
        """

        // MARK: - AppDelegate.swift Template

        static let appDelegateSwift = """
        //
        //  AppDelegate.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //

        import Cocoa

        @main
        class AppDelegate: NSObject, NSApplicationDelegate {

            @IBOutlet var window: NSWindow!

            func applicationDidFinishLaunching(_ aNotification: Notification) {
                print("🎮 Launching {{PROJECT_NAME}}")
            }

            func applicationWillTerminate(_ aNotification: Notification) {
                // Insert code here to tear down your application
            }

            func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
                return true
            }
        }
        """

        // MARK: - GameScene.swift Template

        static let macOSGameSceneSwift = """
        //
        //  GameScene.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //

        import Combine
        import Foundation
        import UntoldEngine

        @MainActor
        final class EngineStatsWindowStore: ObservableObject {
            static let shared = EngineStatsWindowStore()

            @Published var advancedMode: Bool = false
            @Published private(set) var compactText: String = ""
            @Published private(set) var expandedText: String = ""

            private var timer: Timer?

            private init() {
                refresh()
                timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
                    guard let self else { return }
                    Task { @MainActor in
                        self.refresh()
                    }
                }
            }

            deinit {
                timer?.invalidate()
            }

            private func refresh() {
                let snapshot = getEngineStatsSnapshot()
                compactText = formatEngineStatsCompact(snapshot)
                expandedText = formatEngineStatsOverlay(snapshot)
            }
        }

        // GameScene: Initialize your game and write game-specific logic
        class GameScene {

            init() {
                // Configure asset paths
                setupAssetPaths()

                // Load game content
                loadBundledScripts()
                loadAndPlayFirstScene()

                // Start game systems
                startGameSystems()
            }

            // MARK: - Setup Methods

            /// Configure the asset base path for the bundled GameData
            private func setupAssetPaths() {
                if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
                    assetBasePath = gameDataURL
                    Logger.log(message: "✅ Found GameData at: \\(gameDataURL.path)")
                } else if let resourceURL = Bundle.main.resourceURL {
                    let gameDataPath = resourceURL.appendingPathComponent("GameData")
                    if FileManager.default.fileExists(atPath: gameDataPath.path) {
                        assetBasePath = gameDataPath
                        Logger.log(message: "✅ Found GameData in Resources: \\(gameDataPath.path)")
                    } else {
                        Logger.log(message: "⚠️ GameData not found. Bundle resources: \\(resourceURL.path)")
                    }
                }
            }

            /// Load and play the first available scene
            private func loadAndPlayFirstScene() {
                if let sceneURL = findFirstScene() {
                    playSceneAt(url: sceneURL)
                    Logger.log(message: "✅ Scene loaded: \\(sceneURL.lastPathComponent)")
                } else {
                    Logger.log(message: "⚠️ No scene files found")
                }
            }

            /// Start game systems for play mode
            private func startGameSystems() {
                gameMode = true
                AnimationSystem.shared.isEnabled = true
                USCSystem.shared.startPlayMode()
            }

            // MARK: - Asset Loading

            /// Find the first scene in GameData/Scenes
            private func findFirstScene() -> URL? {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    Logger.log(message: "⚠️ GameData directory not found")
                    return nil
                }

                let scenesURL = gameDataURL.appendingPathComponent("Scenes")

                guard let sceneFiles = try? FileManager.default.contentsOfDirectory(
                    at: scenesURL,
                    includingPropertiesForKeys: nil
                ) else {
                    return nil
                }

                return sceneFiles.first(where: { $0.pathExtension == "json" })
            }

            /// Load all USC scripts from GameData/Scripts
            private func loadBundledScripts() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    return
                }

                let scriptsURL = gameDataURL.appendingPathComponent("Scripts")
                let count = loadScripts(from: scriptsURL)
                Logger.log(message: "✅ Loaded \\(count) script(s) from bundle")
            }

            // MARK: - Game Loop

            /// Called every frame - add custom game logic here
            func update(deltaTime _: Float) {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom update logic here
            }

            /// Called for input handling - add custom input logic here
            func handleInput() {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom input handling here
            }
        }
        """

        // MARK: - GameViewController.swift Template

        static let gameViewControllerSwift = """
        //
        //  GameViewController.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //

        import Cocoa
        import MetalKit
        import UntoldEngine

        // GameViewController: Manages the MTKView and renderer
        class GameViewController: NSViewController {

            var renderer: UntoldRenderer!
            var gameScene: GameScene!

            override func viewDidLoad() {
                super.viewDidLoad()

                guard let view = self.view as? MTKView else {
                    print("View attached to GameViewController is not an MTKView")
                    return
                }

                // Select the device to render with
                guard let device = MTLCreateSystemDefaultDevice() else {
                    print("Metal is not supported on this device")
                    return
                }

                view.device = device
                view.depthStencilPixelFormat = .depth32Float
                view.colorPixelFormat = .bgra8Unorm_srgb
                view.preferredFramesPerSecond = 60
                (view.layer as? CAMetalLayer)?.contentsScale = 1.0
                view.framebufferOnly = false

                // Create the renderer
                renderer = UntoldRenderer.create(device: device, view: view)

                // Set the renderer as the view's delegate
                view.delegate = renderer

                // Manually trigger the initial size setup
                renderer.mtkView(view, drawableSizeWillChange: view.drawableSize)

                // Initialize game scene and setup callbacks
                gameScene = GameScene()
                renderer.setupCallbacks(
                    gameUpdate: { [weak self] deltaTime in
                        self?.gameScene.update(deltaTime: deltaTime)
                    },
                    handleInput: { [weak self] in
                        self?.gameScene.handleInput()
                    }
                )
            }
        }
        """

        // MARK: - GameScene.swift Template (optional separate file)

        // Note: GameScene is included in main.swift by default
        // This is provided as reference if developers want to split it out

        static let gameSceneSwift = """
        //
        //  GameRuntime.swift
        //  {{PROJECT_NAME}}
        //
        //  Game runtime that loads and executes game data
        //  Generated by UntoldEngine Build System
        //

        import Foundation
        import UntoldEngine

        /// Lightweight runtime wrapper that loads bundled game data and starts the engine
        class GameRuntime {

            private var loadedScenes: [Scene] = []
            private var loadedScripts: [USCScript] = []

            init() {
                Logger.log(message: "🎮 {{PROJECT_NAME}} Runtime Initialized")
            }

            /// Load all game data from the bundle
            func loadGameData() {
                Logger.log(message: "📦 Loading game data...")

                // Load scenes
                loadScenes()

                // Load USC scripts
                loadScripts()

                // Initialize scripting system
                initScriptingSystem()

                Logger.log(message: "✅ Game data loaded successfully")
            }

            /// Start the game
            func run() {
                Logger.log(message: "🚀 Starting {{PROJECT_NAME}}...")

                // Initialize the engine with first scene
                if let firstScene = loadedScenes.first {
                    initEngine(scene: firstScene)
                } else {
                    Logger.log(message: "⚠️ No scenes found, creating default scene")
                    initEngine(scene: createDefaultScene())
                }

                // Start the main loop
                startGameLoop()
            }

            // MARK: - Private Helpers

            private func loadScenes() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    Logger.log(message: "⚠️ GameData directory not found")
                    return
                }

                let scenesURL = gameDataURL.appendingPathComponent("Scenes")

                guard let sceneFiles = try? FileManager.default.contentsOfDirectory(
                    at: scenesURL,
                    includingPropertiesForKeys: nil
                ) else {
                    Logger.log(message: "⚠️ No scenes directory found")
                    return
                }

                for sceneFile in sceneFiles where sceneFile.pathExtension == "json" {
                    if let scene = loadScene(from: sceneFile) {
                        loadedScenes.append(scene)
                        Logger.log(message: "📄 Loaded scene: \\(scene.name)")
                    }
                }
            }

            private func loadScene(from url: URL) -> Scene? {
                guard let data = try? Data(contentsOf: url),
                      let scene = try? JSONDecoder().decode(Scene.self, from: data) else {
                    Logger.log(message: "❌ Failed to load scene from \\(url.lastPathComponent)")
                    return nil
                }
                return scene
            }

            private func loadScripts() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    return
                }

                let scriptsURL = gameDataURL.appendingPathComponent("Scripts")

                guard let scriptFiles = try? FileManager.default.contentsOfDirectory(
                    at: scriptsURL,
                    includingPropertiesForKeys: nil
                ) else {
                    Logger.log(message: "⚠️ No scripts directory found")
                    return
                }

                for scriptFile in scriptFiles where scriptFile.pathExtension == "uscript" {
                    if let script = loadUSCScript(from: scriptFile) {
                        loadedScripts.append(script)
                        Logger.log(message: "📜 Loaded script: \\(script.name)")
                    }
                }
            }

            private func createDefaultScene() -> Scene {
                let scene = createScene(named: "DefaultScene")
                Logger.log(message: "🎬 Created default scene")
                return scene
            }

            private func startGameLoop() {
                // The engine's main loop will take over from here
                Logger.log(message: "🔄 Game loop started")
            }
        }
        """

        // MARK: - README.md Template

        // MARK: - Main.storyboard Template

        static let mainStoryboard = """
        <?xml version="1.0" encoding="UTF-8"?>
        <document type="com.apple.InterfaceBuilder3.Cocoa.Storyboard.XIB" version="3.0" toolsVersion="23504" targetRuntime="MacOSX.Cocoa" propertyAccessControl="none" useAutolayout="YES" initialViewController="B8D-0N-5wS">
            <dependencies>
                <plugIn identifier="com.apple.InterfaceBuilder.CocoaPlugin" version="23504"/>
                <capability name="Metal" minToolsVersion="11.0"/>
                <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
            </dependencies>
            <scenes>
                <!--Application-->
                <scene sceneID="JPo-4y-FX3">
                    <objects>
                        <application id="hnw-xV-0zn" sceneMemberID="viewController">
                            <menu key="mainMenu" title="Main Menu" systemMenu="main" id="AYu-sK-qS6">
                                <items>
                                    <menuItem title="{{PROJECT_NAME}}" id="1Xt-HY-uBw">
                                        <modifierMask key="keyEquivalentModifierMask"/>
                                        <menu key="submenu" title="{{PROJECT_NAME}}" systemMenu="apple" id="uQy-DD-JDr">
                                            <items>
                                                <menuItem title="Quit {{PROJECT_NAME}}" keyEquivalent="q" id="4sb-4s-VLi">
                                                    <connections>
                                                        <action selector="terminate:" target="hnw-xV-0zn" id="Te7-pn-YzF"/>
                                                    </connections>
                                                </menuItem>
                                            </items>
                                        </menu>
                                    </menuItem>
                                </items>
                            </menu>
                            <connections>
                                <outlet property="delegate" destination="Voe-Tx-rLC" id="PrD-fu-P6m"/>
                            </connections>
                        </application>
                        <customObject id="Voe-Tx-rLC" customClass="AppDelegate" customModule="{{PROJECT_NAME}}" customModuleProvider="target"/>
                        <customObject id="YLy-65-1bz" customClass="NSFontManager"/>
                        <customObject id="Ady-hI-5gd" userLabel="First Responder" customClass="NSResponder" sceneMemberID="firstResponder"/>
                    </objects>
                    <point key="canvasLocation" x="75" y="0.0"/>
                </scene>
                <!--Window Controller-->
                <scene sceneID="R2V-B0-nI4">
                    <objects>
                        <windowController id="B8D-0N-5wS" sceneMemberID="viewController">
                            <window key="window" title="{{PROJECT_NAME}}" allowsToolTipsWhenApplicationIsInactive="NO" autorecalculatesKeyViewLoop="NO" releasedWhenClosed="NO" visibleAtLaunch="NO" frameAutosaveName="" animationBehavior="default" id="IQv-IB-iLA">
                                <windowStyleMask key="styleMask" titled="YES" closable="YES" miniaturizable="YES" resizable="YES"/>
                                <windowPositionMask key="initialPositionMask" leftStrut="YES" rightStrut="YES" topStrut="YES" bottomStrut="YES"/>
                                <rect key="contentRect" x="335" y="390" width="1920" height="1080"/>
                                <rect key="screenRect" x="0.0" y="0.0" width="2560" height="1415"/>
                            </window>
                            <connections>
                                <segue destination="XfG-lQ-9wD" kind="relationship" relationship="window.shadowedContentViewController" id="cq2-FE-JQM"/>
                            </connections>
                        </windowController>
                        <customObject id="Oky-zY-oP4" userLabel="First Responder" customClass="NSResponder" sceneMemberID="firstResponder"/>
                    </objects>
                    <point key="canvasLocation" x="75" y="250"/>
                </scene>
                <!--Game View Controller-->
                <scene sceneID="hIz-AP-VOD">
                    <objects>
                        <viewController id="XfG-lQ-9wD" customClass="GameViewController" customModule="{{PROJECT_NAME}}" customModuleProvider="target" sceneMemberID="viewController">
                            <view key="view" wantsLayer="YES" id="m2S-Jp-Qdl" customClass="MTKView">
                                <rect key="frame" x="0.0" y="0.0" width="1920" height="1080"/>
                                <autoresizingMask key="autoresizingMask"/>
                            </view>
                        </viewController>
                        <customObject id="rHc-nm-qnH" userLabel="First Responder" customClass="NSResponder" sceneMemberID="firstResponder"/>
                    </objects>
                    <point key="canvasLocation" x="75" y="655"/>
                </scene>
            </scenes>
        </document>
        """

        // MARK: - Info.plist Template

        static let infoPlist = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>$(DEVELOPMENT_LANGUAGE)</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>{{BUNDLE_IDENTIFIER}}</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>$(PRODUCT_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>LSApplicationCategoryType</key>
            <string>public.app-category.games</string>
            <key>LSMinimumSystemVersion</key>
            <string>$(MACOSX_DEPLOYMENT_TARGET)</string>
            <key>NSHumanReadableCopyright</key>
            <string>Copyright © 2025. All rights reserved.</string>
            <key>NSMainStoryboardFile</key>
            <string>Main</string>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
        </dict>
        </plist>
        """

        // MARK: - iOS AppDelegate.swift Template

        static let iOSAppDelegateSwift = """
        //
        //  AppDelegate.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //

        import UIKit

        @main
        class AppDelegate: UIResponder, UIApplicationDelegate {

            var window: UIWindow?

            func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                print("🎮 Launching {{PROJECT_NAME}}")
                return true
            }

            func applicationWillResignActive(_ application: UIApplication) {
                // Sent when the application is about to move from active to inactive state.
            }

            func applicationDidEnterBackground(_ application: UIApplication) {
                // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
            }

            func applicationWillEnterForeground(_ application: UIApplication) {
                // Called as part of the transition from the background to the active state.
            }

            func applicationDidBecomeActive(_ application: UIApplication) {
                // Restart any tasks that were paused (or not yet started) while the application was inactive.
            }
        }
        """

        // MARK: - iOS GameScene.swift Template

        static let iOSGameSceneSwift = """
        //
        //  GameScene.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //

        import Foundation
        import UntoldEngine

        // GameScene: Initialize your game and write game-specific logic
        class GameScene {

            init() {
                // Configure asset paths
                setupAssetPaths()

                // Load game content
                loadBundledScripts()
                loadAndPlayFirstScene()

                // Start game systems
                startGameSystems()
            }

            // MARK: - Setup Methods

            /// Configure the asset base path for the bundled GameData
            private func setupAssetPaths() {
                if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
                    assetBasePath = gameDataURL
                    Logger.log(message: "✅ Found GameData at: \\(gameDataURL.path)")
                } else if let resourceURL = Bundle.main.resourceURL {
                    let gameDataPath = resourceURL.appendingPathComponent("GameData")
                    if FileManager.default.fileExists(atPath: gameDataPath.path) {
                        assetBasePath = gameDataPath
                        Logger.log(message: "✅ Found GameData in Resources: \\(gameDataPath.path)")
                    } else {
                        Logger.log(message: "⚠️ GameData not found. Bundle resources: \\(resourceURL.path)")
                    }
                }
            }

            /// Load and play the first available scene
            private func loadAndPlayFirstScene() {
                if let sceneURL = findFirstScene() {
                    playSceneAt(url: sceneURL)
                    Logger.log(message: "✅ Scene loaded: \\(sceneURL.lastPathComponent)")
                } else {
                    Logger.log(message: "⚠️ No scene files found")
                }
            }

            /// Start game systems for play mode
            private func startGameSystems() {
                gameMode = true
                AnimationSystem.shared.isEnabled = true
                USCSystem.shared.startPlayMode()
            }

            // MARK: - Asset Loading

            /// Find the first scene in GameData/Scenes
            private func findFirstScene() -> URL? {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    Logger.log(message: "⚠️ GameData directory not found")
                    return nil
                }

                let scenesURL = gameDataURL.appendingPathComponent("Scenes")

                guard let sceneFiles = try? FileManager.default.contentsOfDirectory(
                    at: scenesURL,
                    includingPropertiesForKeys: nil
                ) else {
                    return nil
                }

                return sceneFiles.first(where: { $0.pathExtension == "json" })
            }

            /// Load all USC scripts from GameData/Scripts
            private func loadBundledScripts() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    return
                }

                let scriptsURL = gameDataURL.appendingPathComponent("Scripts")
                let count = loadScripts(from: scriptsURL)
                Logger.log(message: "✅ Loaded \\(count) script(s) from bundle")
            }

            // MARK: - Game Loop

            /// Called every frame - add custom game logic here
            func update(deltaTime _: Float) {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom update logic here
            }

            /// Called for input handling - add custom input logic here
            func handleInput() {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom input handling here
            }
        }
        """

        // MARK: - iOS GameViewController.swift Template

        static let iOSGameViewControllerSwift = """
        //
        //  GameViewController.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //

        import UIKit
        import MetalKit
        import UntoldEngine

        // GameViewController: Manages the MTKView and renderer
        class GameViewController: UIViewController {

            var renderer: UntoldRenderer!
            var mtkView: MTKView!
            var gameScene: GameScene!

            override func viewDidLoad() {
                super.viewDidLoad()

                guard let mtkView = view as? MTKView else {
                    print("View of GameViewController is not an MTKView")
                    return
                }

                self.mtkView = mtkView

                // Select the device to render with
                guard let device = MTLCreateSystemDefaultDevice() else {
                    print("Metal is not supported on this device")
                    return
                }

                mtkView.device = device
                view.backgroundColor = UIColor.clear
                mtkView.colorPixelFormat = .bgra8Unorm_srgb
                mtkView.depthStencilPixelFormat = .depth32Float
                mtkView.preferredFramesPerSecond = 60

                // Create the renderer
                guard let newRenderer = UntoldRenderer.createiOS(device: device, view: mtkView) else {
                    print("Failed to initialize the renderer")
                    return
                }

                renderer = newRenderer

                // Set the renderer as the view's delegate
                mtkView.delegate = renderer

                // Manually trigger the initial size setup
                renderer.mtkView(mtkView, drawableSizeWillChange: mtkView.drawableSize)

                // Initialize game scene and setup callbacks
                gameScene = GameScene()
                renderer.setupCallbacks(
                    gameUpdate: { [weak self] deltaTime in
                        self?.gameScene.update(deltaTime: deltaTime)
                    },
                    handleInput: { [weak self] in
                        self?.gameScene.handleInput()
                    }
                )
            }

            override var prefersStatusBarHidden: Bool {
                return true
            }

            override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
                return .landscape
            }
        }
        """

        // MARK: - iOS AR GameScene.swift Template

        static let iOSARGameSceneSwift = """
        //
        //  GameScene.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //  iOS AR Version
        //

        import Foundation
        import UntoldEngine

        // GameScene: Initialize your game and write game-specific logic
        class GameScene {

            init() {
                // Configure asset paths
                setupAssetPaths()

                // Load game content
                loadBundledScripts()
                loadAndPlayFirstScene()

                // Start game systems
                startGameSystems()
            }

            // MARK: - Setup Methods

            /// Configure the asset base path for the bundled GameData
            private func setupAssetPaths() {
                if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
                    assetBasePath = gameDataURL
                    Logger.log(message: "✅ Found GameData at: \\(gameDataURL.path)")
                } else if let resourceURL = Bundle.main.resourceURL {
                    let gameDataPath = resourceURL.appendingPathComponent("GameData")
                    if FileManager.default.fileExists(atPath: gameDataPath.path) {
                        assetBasePath = gameDataPath
                        Logger.log(message: "✅ Found GameData in Resources: \\(gameDataPath.path)")
                    } else {
                        Logger.log(message: "⚠️ GameData not found. Bundle resources: \\(resourceURL.path)")
                    }
                }
            }

            /// Load and play the first available scene
            private func loadAndPlayFirstScene() {
                if let sceneURL = findFirstScene() {
                    playSceneAt(url: sceneURL)
                    Logger.log(message: "✅ Scene loaded: \\(sceneURL.lastPathComponent)")
                } else {
                    Logger.log(message: "⚠️ No scene files found")
                }
            }

            /// Start game systems for play mode
            private func startGameSystems() {
                gameMode = true
                AnimationSystem.shared.isEnabled = true
                USCSystem.shared.startPlayMode()
            }

            // MARK: - Asset Loading

            /// Find the first scene in GameData/Scenes
            private func findFirstScene() -> URL? {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    Logger.log(message: "⚠️ GameData directory not found")
                    return nil
                }

                let scenesURL = gameDataURL.appendingPathComponent("Scenes")

                guard let sceneFiles = try? FileManager.default.contentsOfDirectory(
                    at: scenesURL,
                    includingPropertiesForKeys: nil
                ) else {
                    return nil
                }

                return sceneFiles.first(where: { $0.pathExtension == "json" })
            }

            /// Load all USC scripts from GameData/Scripts
            private func loadBundledScripts() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    return
                }

                let scriptsURL = gameDataURL.appendingPathComponent("Scripts")
                let count = loadScripts(from: scriptsURL)
                Logger.log(message: "✅ Loaded \\(count) script(s) from bundle")
            }

            // MARK: - Game Loop

            /// Called every frame - add custom game logic here
            func update(deltaTime _: Float) {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom update logic here
            }

            /// Called for input handling - add custom input logic here
            func handleInput() {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom input handling here
            }
        }
        """

        // MARK: - iOS AR GameViewController.swift Template

        static let iOSARGameViewControllerSwift = """
        //
        //  GameViewController.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //  iOS AR Version
        //

        import UIKit
        import MetalKit
        import ARKit
        import UntoldEngineAR

        // GameViewController: Manages the MTKView and AR renderer
        class GameViewController: UIViewController, MTKViewDelegate, ARSessionDelegate {

            var renderer: UntoldEngineAR!
            var mtkView: MTKView!
            var gameScene: GameScene!
            var arSession: ARSession!

            override func viewDidLoad() {
                super.viewDidLoad()

                // Create ARSession FIRST (needed by renderer)
                arSession = ARSession()
                arSession.delegate = self

                guard let mtkView = view as? MTKView else {
                    print("View of GameViewController is not an MTKView")
                    return
                }

                self.mtkView = mtkView

                // Select the device to render with
                guard let device = MTLCreateSystemDefaultDevice() else {
                    print("Metal is not supported on this device")
                    return
                }

                mtkView.device = device
                view.backgroundColor = UIColor.clear
                mtkView.colorPixelFormat = .bgra8Unorm_srgb
                mtkView.depthStencilPixelFormat = .depth32Float
                mtkView.preferredFramesPerSecond = 60

                // Create the AR renderer with session
                renderer = UntoldEngineAR(session: arSession, device: device, view: mtkView)

                // Set this controller as the view's delegate
                mtkView.delegate = self

                // Initialize game scene and setup callbacks
                gameScene = GameScene()
                renderer.setupCallbacks(
                    gameUpdate: { [weak self] deltaTime in
                        self?.gameScene.update(deltaTime: deltaTime)
                    },
                    handleInput: { [weak self] in
                        self?.gameScene.handleInput()
                    }
                )
            }

            override func viewWillAppear(_ animated: Bool) {
                super.viewWillAppear(animated)

                // Start AR session
                let configuration = ARWorldTrackingConfiguration()
                configuration.planeDetection = [.horizontal, .vertical]
                configuration.environmentTexturing = .automatic

                arSession.run(configuration)
                Logger.log(message: "🎯 AR Session started")
            }

            override func viewWillDisappear(_ animated: Bool) {
                super.viewWillDisappear(animated)
                arSession.pause()
            }

                override var prefersStatusBarHidden: Bool {
                    return true
                }

                override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
                    return .landscape
                }

            // MARK: - MTKViewDelegate

            func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize) {
                renderer.drawRectResized(size: size)
            }

            func draw(in view: MTKView) {
                renderer.draw(in: view)
            }

            // MARK: - ARSessionDelegate

            func session(_ session: ARSession, didFailWithError error: Error) {
            }

            func sessionWasInterrupted(_ session: ARSession) {
            }

            func sessionInterruptionEnded(_ session: ARSession) {
            }
        }
        """

        // MARK: - iOS Main.storyboard Template

        static let iOSMainStoryboard = """
        <?xml version="1.0" encoding="UTF-8"?>
        <document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="23504" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES" initialViewController="BV1-FR-VrT">
            <device id="retina6_12" orientation="landscape" appearance="light"/>
            <dependencies>
                <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="23504"/>
                <capability name="Metal" minToolsVersion="11.0"/>
                <capability name="Safe area layout guides" minToolsVersion="9.0"/>
                <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
            </dependencies>
            <scenes>
                <!--Game View Controller-->
                <scene sceneID="tXr-a1-R10">
                    <objects>
                        <viewController id="BV1-FR-VrT" customClass="GameViewController" customModule="{{PROJECT_NAME}}" customModuleProvider="target" sceneMemberID="viewController">
                            <view key="view" contentMode="scaleToFill" id="3se-qz-xqx" customClass="MTKView">
                                <rect key="frame" x="0.0" y="0.0" width="852" height="393"/>
                                <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                                <viewLayoutGuide key="safeArea" id="4qk-I5-YsI"/>
                            </view>
                        </viewController>
                        <placeholder placeholderIdentifier="IBFirstResponder" id="SZV-WD-TEh" sceneMemberID="firstResponder"/>
                    </objects>
                    <point key="canvasLocation" x="140" y="130"/>
                </scene>
            </scenes>
        </document>
        """

        // MARK: - iOS Info.plist Template

        static let iOSInfoPlist = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>$(DEVELOPMENT_LANGUAGE)</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>$(PRODUCT_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>UIApplicationSceneManifest</key>
            <dict>
                <key>UIApplicationSupportsMultipleScenes</key>
                <false/>
            </dict>
            <key>UILaunchStoryboardName</key>
            <string>Main</string>
            <key>UIMainStoryboardFile</key>
            <string>Main</string>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
                <string>armv7</string>
                <string>metal</string>
            </array>
            <key>UIStatusBarHidden</key>
            <true/>
            <key>UISupportedInterfaceOrientations</key>
            <array>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
            <key>UISupportedInterfaceOrientations~ipad</key>
            <array>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
        </dict>
        </plist>
        """

        // MARK: - iOS AR Info.plist Template (includes AR permissions)

        static let iOSARInfoPlist = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>$(DEVELOPMENT_LANGUAGE)</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>$(PRODUCT_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>NSCameraUsageDescription</key>
            <string>This app requires camera access for AR features</string>
            <key>UIApplicationSceneManifest</key>
            <dict>
                <key>UIApplicationSupportsMultipleScenes</key>
                <false/>
            </dict>
            <key>UILaunchStoryboardName</key>
            <string>Main</string>
            <key>UIMainStoryboardFile</key>
            <string>Main</string>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
                <string>armv7</string>
                <string>metal</string>
                <string>arkit</string>
            </array>
            <key>UIStatusBarHidden</key>
            <true/>
            <key>UISupportedInterfaceOrientations</key>
            <array>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
            <key>UISupportedInterfaceOrientations~ipad</key>
            <array>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
        </dict>
        </plist>
        """

        // MARK: - visionOS GameScene.swift Template

        static let visionOSGameSceneSwift = """
        //
        //  GameScene.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //  visionOS Version
        //

        import Foundation
        import UntoldEngine

        // GameScene: Initialize your game and write game-specific logic
        class GameScene {

        init() {
            Logger.log(message: "🎮 GameScene initializing...")

            // Configure asset paths with debug logging
            logBundleInfo()
            setupAssetPaths()

            // Load game content
            Logger.log(message: "📜 Loading bundled scripts...")
            loadBundledScripts()

            Logger.log(message: "🎬 Searching for scene files...")
            loadAndPlayFirstScene()

            // Start game systems
            startGameSystems()

            Logger.log(message: "✅ GameScene initialization complete")
        }

        // MARK: - Setup Methods

        /// Log bundle information for debugging
        private func logBundleInfo() {
            Logger.log(message: "📦 Bundle path: \\(Bundle.main.bundlePath)")
            if let resourceURL = Bundle.main.resourceURL {
                Logger.log(message: "📦 Resource URL: \\(resourceURL.path)")
                if let contents = try? FileManager.default.contentsOfDirectory(atPath: resourceURL.path) {
                    Logger.log(message: "📦 Resources directory contents: \\(contents.joined(separator: ", "))")
                }
            }
        }

        /// Configure the asset base path for the bundled GameData
        private func setupAssetPaths() {
            if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
                assetBasePath = gameDataURL
                Logger.log(message: "✅ Found GameData at: \\(gameDataURL.path)")
                if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataURL.path) {
                    Logger.log(message: "📦 GameData contents: \\(contents.joined(separator: ", "))")
                }
            } else if let resourceURL = Bundle.main.resourceURL {
                let gameDataPath = resourceURL.appendingPathComponent("GameData")
                if FileManager.default.fileExists(atPath: gameDataPath.path) {
                    assetBasePath = gameDataPath
                    Logger.log(message: "✅ Found GameData in Resources: \\(gameDataPath.path)")
                    if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataPath.path) {
                        Logger.log(message: "📦 GameData contents: \\(contents.joined(separator: ", "))")
                    }
                } else {
                    Logger.log(message: "⚠️ GameData not found. Bundle resources: \\(resourceURL.path)")
                    Logger.log(message: "⚠️ Listing all files in bundle resources...")
                    listDirectoryRecursively(at: resourceURL)
                }
            } else {
                Logger.log(message: "❌ Bundle.main.resourceURL is nil!")
            }
        }

        /// Load and play the first available scene
        private func loadAndPlayFirstScene() {
            if let sceneURL = findFirstScene() {
                Logger.log(message: "✅ Found scene: \\(sceneURL.lastPathComponent)")
                playSceneAt(url: sceneURL)
                Logger.log(message: "✅ Scene loaded: \\(sceneURL.lastPathComponent)")
            } else {
                Logger.log(message: "⚠️ No scene files found - nothing will render")
                Logger.log(message: "⚠️ Create a scene in the editor and rebuild the project")
            }
        }

        /// Start game systems for play mode
        private func startGameSystems() {
            gameMode = true
            AnimationSystem.shared.isEnabled = true
            USCSystem.shared.startPlayMode()
        }

        // MARK: - Asset Loading

        /// Recursively list directory contents for debugging
        private func listDirectoryRecursively(at url: URL, depth: Int = 0) {
            let indent = String(repeating: "  ", count: depth)
            guard let contents = try? FileManager.default.contentsOfDirectory(atPath: url.path) else {
                return
            }
            for item in contents {
                let itemURL = url.appendingPathComponent(item)
                var isDirectory: ObjCBool = false
                if FileManager.default.fileExists(atPath: itemURL.path, isDirectory: &isDirectory) {
                    Logger.log(message: "\\(indent)📁 \\(item)\\(isDirectory.boolValue ? "/" : "")")
                    if isDirectory.boolValue && depth < 2 {
                        listDirectoryRecursively(at: itemURL, depth: depth + 1)
                    }
                }
            }
        }

            /// Find the first scene in GameData/Scenes
            private func findFirstScene() -> URL? {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    Logger.log(message: "⚠️ GameData directory not found")
                    return nil
                }

                let scenesURL = gameDataURL.appendingPathComponent("Scenes")

                guard let sceneFiles = try? FileManager.default.contentsOfDirectory(
                    at: scenesURL,
                    includingPropertiesForKeys: nil
                ) else {
                    return nil
                }

                return sceneFiles.first(where: { $0.pathExtension == "json" })
            }

            /// Load all USC scripts from GameData/Scripts
            private func loadBundledScripts() {
                guard let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) else {
                    return
                }

                let scriptsURL = gameDataURL.appendingPathComponent("Scripts")
                let count = loadScripts(from: scriptsURL)
                Logger.log(message: "✅ Loaded \\(count) script(s) from bundle")
            }

            // MARK: - Game Loop

            /// Called every frame - add custom game logic here
            func update(deltaTime _: Float) {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom update logic here
            }

            /// Called for input handling - add custom input logic here
            func handleInput() {
                // Skip logic if not in game mode
                if gameMode == false { return }

                // Add your custom input handling here
            }
        }
        """

        // MARK: - visionOS App.swift Template

        static let visionOSAppSwift = """
        //
        //  {{PROJECT_NAME}}App.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //  visionOS Version
        //

        import SwiftUI
        import CompositorServices
        import UntoldEngineXR

        // Simple owner so the XR system doesn't deallocate.
        final class XRHolder {
            static let shared = XRHolder()
            var xr: UntoldEngineXR?
            var renderThread: Thread?
        }

        struct UntoldEngineConfiguration: CompositorLayerConfiguration {
            func makeConfiguration(capabilities: LayerRenderer.Capabilities,
                                   configuration: inout LayerRenderer.Configuration) {
                configuration.layout = .dedicated
                configuration.isFoveationEnabled = false
                configuration.colorFormat = .bgra8Unorm_srgb
            }
        }

        @main
        struct {{PROJECT_NAME}}App: App {

            @State private var immersionStyle: ImmersionStyle = .mixed

            var body: some Scene {
                WindowGroup {
                    ContentView()
                }
                .windowStyle(.plain)
                .defaultSize(width: 600, height: 400)

                WindowGroup("Engine Stats", id: "EngineStatsPanel") {
                    EngineStatsWindowView(store: EngineStatsWindowStore.shared)
                }
                .defaultSize(width: 720, height: 340)

            ImmersiveSpace(id: "ImmersiveSpace") {

                CompositorLayer(configuration: UntoldEngineConfiguration(), renderer: { layerRenderer in

                    // init + retain XR system
                    if XRHolder.shared.xr == nil {

                        if let xr = UntoldEngineXR(layerRenderer: layerRenderer) {
                            XRHolder.shared.xr = xr

                            // Set engine's immersion mode to mixed (passthrough)
                            xr.setImmersionMode(xrImmersionMode: .mixed)

                            // Initialize game scene
                            let gameScene = GameScene()

                            // Setup callbacks
                            xr.setupCallbacks(
                                gameUpdate: { deltaTime in
                                    gameScene.update(deltaTime: deltaTime)
                                },
                                handleInput: {
                                    gameScene.handleInput()
                                }
                            )

                            let t = Thread {
                                xr.start()      // sets isRunning = true
                                xr.runLoop()    // blocking loop - runs on dedicated thread, NOT MainActor
                            }
                            t.name = "XR Render Thread"
                            t.qualityOfService = .userInteractive
                            XRHolder.shared.renderThread = t
                            t.start()
                        } else {
                            print("❌ Failed to initialize UntoldEngineXR!")
                            print("❌ LayerRenderer might be invalid or engine initialization failed")
                        }
                    } else {
                        print("⚠️ XR system already initialized")
                    }
                })
            }
                .immersionStyle(selection: $immersionStyle, in: .mixed)
            }
        }

        struct ContentView: View {
            @Environment(\\.openImmersiveSpace) private var openImmersiveSpace
            @Environment(\\.openWindow) private var openWindow

            var body: some View {
                VStack(spacing: 30) {
                    Text("{{PROJECT_NAME}}")
                        .font(.extraLargeTitle)
                        .fontWeight(.bold)

                    Text("Powered by UntoldEngine")
                        .font(.title)
                        .foregroundColor(.secondary)

                Button(action: {
                    Task {
                        await openImmersiveSpace(id: "ImmersiveSpace")
                    }
                }) {
                        Label("Start Experience", systemImage: "visionpro.fill")
                            .frame(minWidth: 250)
                    }
                    .buttonStyle(.borderedProminent)
                    .controlSize(.large)

                    Button(action: {
                        openWindow(id: "EngineStatsPanel")
                    }) {
                        Label("Engine Stats", systemImage: "chart.xyaxis.line")
                            .frame(minWidth: 250)
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.large)
                }
                .padding(60)
            }
        }

        struct EngineStatsWindowView: View {
            @ObservedObject var store: EngineStatsWindowStore

            var body: some View {
                VStack(alignment: .leading, spacing: 12) {
                    HStack {
                        Text("Engine Stats")
                            .font(.headline)
                        Spacer()
                        Toggle("Advanced", isOn: $store.advancedMode)
                            .toggleStyle(.switch)
                            .controlSize(.small)
                    }

                    ScrollView {
                        Text(store.advancedMode ? store.expandedText : store.compactText)
                            .font(.system(size: 12, design: .monospaced))
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .textSelection(.enabled)
                    }
                }
                .padding(16)
            }
        }
        """

        // MARK: - visionOS Info.plist Template

        static let visionOSInfoPlist = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>$(DEVELOPMENT_LANGUAGE)</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>$(PRODUCT_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>UIApplicationSceneManifest</key>
            <dict>
                <key>UIApplicationPreferredDefaultSceneSessionRole</key>
                <string>UIWindowSceneSessionRoleApplication</string>
                <key>UIApplicationSupportsMultipleScenes</key>
                <true/>
            </dict>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
                <string>metal</string>
            </array>
            <key>NSWorldSensingUsageDescription</key>
            <string>{{PROJECT_NAME}} uses world sensing to provide immersive AR experiences.</string>
        </dict>
        </plist>
        """

        // MARK: - README.md Template

        static let readmeMd = """
        # {{PROJECT_NAME}}

        Generated by **UntoldEngine Build System**

        ## 🎮 About

        This is a macOS game project built with UntoldEngine. The project includes all your game data (scenes, scripts, assets) bundled and ready to run.

        ## 🚀 Quick Start

        ### Build and Run

        ```bash
        swift build
        swift run
        ```

        ### Open in Xcode

        ```bash
        open Package.swift
        ```

        Then press `Cmd+R` to build and run.

        ## 📁 Project Structure

        ```
        {{PROJECT_NAME}}/
        ├── Package.swift              # Swift Package configuration
        ├── README.md              
        └── Sources/
            └── {{PROJECT_NAME}}/
                ├── main.swift         # Entry point
                ├── GameRuntime.swift  # Game loader
                └── GameData/          # Bundled game content
                    ├── Scenes/        # Scene files (.json)
                    ├── Scripts/       # USC scripts (.uscript)
                    ├── Models/        # 3D models
                    ├── Textures/      # Texture files
                    └── Shaders/       # Compiled Metal shaders
        ```

        ## 🎯 Requirements

        - macOS {{MACOS_VERSION}} or later
        - Xcode 15.0 or later
        - Swift 5.9 or later

        ## 📝 Notes

        - This project uses UntoldEngine as a Swift Package dependency from GitHub
        - All game data is bundled as resources
        - USC scripts are loaded and executed at runtime

        ## 🔗 UntoldEngine

        Powered by [UntoldEngine](https://github.com/untoldengine/UntoldEngine)

        ---

        Built with ❤️ using UntoldEngine
        """

        // MARK: - Multi-Platform Templates

        /// Unified GameScene template that works across all platforms
        static let multiPlatformGameSceneSwift = macOSGameSceneSwift

        /// Multi-platform AppDelegate/App with conditional compilation
        static let multiPlatformAppDelegateSwift = """
        //
        //  AppDelegate.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //  Multi-Platform Support
        //

        #if os(macOS)
        import Cocoa

        @main
        class AppDelegate: NSObject, NSApplicationDelegate {

            @IBOutlet var window: NSWindow!

            func applicationDidFinishLaunching(_ aNotification: Notification) {
                print("🎮 Launching {{PROJECT_NAME}} on macOS")
            }

            func applicationWillTerminate(_ aNotification: Notification) {
                // Insert code here to tear down your application
            }

            func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
                return true
            }
        }

        #elseif os(iOS)
        import UIKit

        @main
        class AppDelegate: UIResponder, UIApplicationDelegate {

            var window: UIWindow?

            func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                print("🎮 Launching {{PROJECT_NAME}} on iOS")
                return true
            }

            func applicationWillResignActive(_ application: UIApplication) {
                // Sent when the application is about to move from active to inactive state.
            }

            func applicationDidEnterBackground(_ application: UIApplication) {
                // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
            }

            func applicationWillEnterForeground(_ application: UIApplication) {
                // Called as part of the transition from the background to the active state.
            }

            func applicationDidBecomeActive(_ application: UIApplication) {
                // Restart any tasks that were paused (or not yet started) while the application was inactive.
            }
        }

        #elseif os(visionOS)
        import SwiftUI
        import CompositorServices
        import UntoldEngineXR

        // Simple owner so the XR system doesn't deallocate.
        final class XRHolder {
            static let shared = XRHolder()
            var xr: UntoldEngineXR?
            var renderThread: Thread?
        }

        @main
        struct {{PROJECT_NAME}}App: App {
            @State private var immersionStyle: ImmersionStyle = .full

            var body: some Scene {
                ImmersiveSpace(id: "GameSpace") {
                    CompositorLayer(configuration: ContentStageConfiguration()) { layerRenderer in
                        print("🎮 Launching {{PROJECT_NAME}} on visionOS")
                        let xr = UntoldEngineXR(layerRenderer: layerRenderer)
                        XRHolder.shared.xr = xr

                        let renderThread = Thread {
                            xr.startRenderLoop()
                        }
                        renderThread.name = "RenderThread"
                        XRHolder.shared.renderThread = renderThread
                        renderThread.start()
                    }
                }
                .immersionStyle(selection: $immersionStyle, in: .full)
            }
        }
        #endif
        """

        /// Multi-platform GameViewController with conditional compilation
        static let multiPlatformGameViewControllerSwift = """
        //
        //  GameViewController.swift
        //  {{PROJECT_NAME}}
        //
        //  Generated by UntoldEngine Build System
        //  Multi-Platform Support
        //

        #if os(macOS)
        import Cocoa
        import MetalKit
        import UntoldEngine

        // GameViewController: Manages the MTKView and renderer
        class GameViewController: NSViewController {

            var renderer: UntoldRenderer!
            var gameScene: GameScene!

            override func viewDidLoad() {
                super.viewDidLoad()

                guard let view = self.view as? MTKView else {
                    print("View attached to GameViewController is not an MTKView")
                    return
                }

                // Select the device to render with
                guard let device = MTLCreateSystemDefaultDevice() else {
                    print("Metal is not supported on this device")
                    return
                }

                view.device = device
                view.depthStencilPixelFormat = .depth32Float
                view.colorPixelFormat = .bgra8Unorm_srgb
                view.preferredFramesPerSecond = 60
                (view.layer as? CAMetalLayer)?.contentsScale = 1.0
                view.framebufferOnly = false

                // Create the renderer
                renderer = UntoldRenderer.create(device: device, view: view)

                // Set the renderer as the view's delegate
                view.delegate = renderer

                // Manually trigger the initial size setup
                renderer.mtkView(view, drawableSizeWillChange: view.drawableSize)

                // Initialize game scene and setup callbacks
                gameScene = GameScene()
                renderer.setupCallbacks(
                    gameUpdate: { [weak self] deltaTime in
                        self?.gameScene.update(deltaTime: deltaTime)
                    },
                    handleInput: { [weak self] in
                        self?.gameScene.handleInput()
                    }
                )
            }
        }

        #elseif os(iOS)
        import UIKit
        import MetalKit
        import UntoldEngine

        // GameViewController: Manages the MTKView and renderer
        class GameViewController: UIViewController {

            var renderer: UntoldRenderer!
            var mtkView: MTKView!
            var gameScene: GameScene!

            override func viewDidLoad() {
                super.viewDidLoad()

                guard let mtkView = view as? MTKView else {
                    print("View of GameViewController is not an MTKView")
                    return
                }

                self.mtkView = mtkView

                // Select the device to render with
                guard let device = MTLCreateSystemDefaultDevice() else {
                    print("Metal is not supported on this device")
                    return
                }

                mtkView.device = device
                view.backgroundColor = UIColor.clear
                mtkView.colorPixelFormat = .bgra8Unorm_srgb
                mtkView.depthStencilPixelFormat = .depth32Float
                mtkView.preferredFramesPerSecond = 60

                // Create the renderer
                guard let newRenderer = UntoldRenderer.createiOS(device: device, view: mtkView) else {
                    print("Failed to initialize the renderer")
                    return
                }

                renderer = newRenderer

                // Set the renderer as the view's delegate
                mtkView.delegate = renderer

                // Manually trigger the initial size setup
                renderer.mtkView(mtkView, drawableSizeWillChange: mtkView.drawableSize)

                // Initialize game scene and setup callbacks
                gameScene = GameScene()
                renderer.setupCallbacks(
                    gameUpdate: { [weak self] deltaTime in
                        self?.gameScene.update(deltaTime: deltaTime)
                    },
                    handleInput: { [weak self] in
                        self?.gameScene.handleInput()
                    }
                )
            }

            override var prefersStatusBarHidden: Bool {
                return true
            }

            override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
                return .landscape
            }
        }

        #elseif os(visionOS)
        // visionOS doesn't use a GameViewController - rendering is handled via CompositorLayer in the App
        // GameScene is initialized within the UntoldEngineXR system
        #endif
        """

        /// Multi-platform Info.plist with platform-specific keys
        static let multiPlatformInfoPlist = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>$(DEVELOPMENT_LANGUAGE)</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>$(PRODUCT_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
                <string>metal</string>
            </array>
        </dict>
        </plist>
        """

        // MARK: - Helper Methods

        /// Get all template files for a target
        static func getTemplateFiles(for target: BuildTarget) -> [String: String] {
            switch target {
            case .macOS:
                return [
                    "Package.swift": packageSwift,
                    "README.md": readmeMd,
                    "Sources/{{PROJECT_NAME}}/AppDelegate.swift": appDelegateSwift,
                    "Sources/{{PROJECT_NAME}}/GameScene.swift": macOSGameSceneSwift,
                    "Sources/{{PROJECT_NAME}}/GameViewController.swift": gameViewControllerSwift,
                    "Sources/{{PROJECT_NAME}}/Base.lproj/Main.storyboard": mainStoryboard,
                    "Sources/{{PROJECT_NAME}}/Info.plist": infoPlist,
                ]
            case .iOS:
                return [
                    "README.md": readmeMd,
                    "Sources/{{PROJECT_NAME}}/AppDelegate.swift": iOSAppDelegateSwift,
                    "Sources/{{PROJECT_NAME}}/GameScene.swift": iOSGameSceneSwift,
                    "Sources/{{PROJECT_NAME}}/GameViewController.swift": iOSGameViewControllerSwift,
                    "Sources/{{PROJECT_NAME}}/Base.lproj/Main.storyboard": iOSMainStoryboard,
                    "Sources/{{PROJECT_NAME}}/Info.plist": iOSInfoPlist,
                ]
            case .visionOS:
                // VisionOS uses SwiftUI App structure with CompositorLayer
                return [
                    "README.md": readmeMd,
                    "Sources/{{PROJECT_NAME}}/GameScene.swift": visionOSGameSceneSwift,
                    "Sources/{{PROJECT_NAME}}/{{PROJECT_NAME}}App.swift": visionOSAppSwift,
                    "Sources/{{PROJECT_NAME}}/Info.plist": visionOSInfoPlist,
                ]
            case .multi:
                // Multi-platform projects use the dedicated multi-platform templates
                return getTemplateFilesForMultiPlatform()
            }
        }

        /// Get template files for iOS AR specifically
        static func getTemplateFilesForIOSAR() -> [String: String] {
            [
                "README.md": readmeMd,
                "Sources/{{PROJECT_NAME}}/AppDelegate.swift": iOSAppDelegateSwift,
                "Sources/{{PROJECT_NAME}}/GameScene.swift": iOSARGameSceneSwift,
                "Sources/{{PROJECT_NAME}}/GameViewController.swift": iOSARGameViewControllerSwift,
                "Sources/{{PROJECT_NAME}}/Base.lproj/Main.storyboard": iOSMainStoryboard,
                "Sources/{{PROJECT_NAME}}/Info.plist": iOSARInfoPlist,
            ]
        }

        /// Get template files for multi-platform projects
        /// Structure: Platform-specific folders + Sources/{ProjectName}/ for shared code
        static func getTemplateFilesForMultiPlatform() -> [String: String] {
            [
                "README.md": readmeMd,

                // macOS target - platform-specific files
                "{{PROJECT_NAME}} macOS/AppDelegate.swift": appDelegateSwift,
                "{{PROJECT_NAME}} macOS/GameViewController.swift": gameViewControllerSwift,
                "{{PROJECT_NAME}} macOS/Base.lproj/Main.storyboard": mainStoryboard,
                "{{PROJECT_NAME}} macOS/Info.plist": infoPlist,

                // iOS target - platform-specific files
                "{{PROJECT_NAME}} iOS/AppDelegate.swift": iOSAppDelegateSwift,
                "{{PROJECT_NAME}} iOS/GameViewController.swift": iOSGameViewControllerSwift,
                "{{PROJECT_NAME}} iOS/Base.lproj/Main.storyboard": iOSMainStoryboard,
                "{{PROJECT_NAME}} iOS/Info.plist": iOSInfoPlist,

                // iOS AR target - platform-specific files
                "{{PROJECT_NAME}} iOS AR/AppDelegate.swift": iOSAppDelegateSwift,
                "{{PROJECT_NAME}} iOS AR/GameViewController.swift": iOSARGameViewControllerSwift,
                "{{PROJECT_NAME}} iOS AR/Base.lproj/Main.storyboard": iOSMainStoryboard,
                "{{PROJECT_NAME}} iOS AR/Info.plist": iOSARInfoPlist,

                // visionOS target - platform-specific files
                "{{PROJECT_NAME}} visionOS/{{PROJECT_NAME}}App.swift": visionOSAppSwift,
                "{{PROJECT_NAME}} visionOS/Info.plist": visionOSInfoPlist,

                // Shared code - in Sources folder (accessible to all targets)
                "Sources/{{PROJECT_NAME}}/GameScene.swift": macOSGameSceneSwift,
            ]
        }
    }

#endif // os(macOS)
