name: Test deployment

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/test-deploy.yml'

jobs:
  test-deploy:
    name: Test MkDocs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Test build docs
        run: mkdocs build --strict
