//
//  GameViewController.swift
//  SampleProject
//
//  Generated by UntoldEngine Build System
//

import Cocoa
import MetalKit
import UntoldEngine

// GameViewController: Manages the MTKView and renderer
class GameViewController: NSViewController {
    var renderer: UntoldRenderer!
    var gameScene: GameScene!

    override func viewDidLoad() {
        super.viewDidLoad()

        guard let view = view as? MTKView else {
            print("View attached to GameViewController is not an MTKView")
            return
        }

        // Select the device to render with
        guard let device = MTLCreateSystemDefaultDevice() else {
            print("Metal is not supported on this device")
            return
        }

        view.device = device
        view.depthStencilPixelFormat = .depth32Float
        view.colorPixelFormat = .bgra8Unorm_srgb
        view.preferredFramesPerSecond = 60
        (view.layer as? CAMetalLayer)?.contentsScale = 1.0
        view.framebufferOnly = false

        // Create the renderer
        renderer = UntoldRenderer.create(device: device, view: view)

        // Set the renderer as the view's delegate
        view.delegate = renderer

        // Manually trigger the initial size setup
        renderer.mtkView(view, drawableSizeWillChange: view.drawableSize)

        // Initialize game scene and setup callbacks
        gameScene = GameScene()
        renderer.setupCallbacks(
            gameUpdate: { [weak self] deltaTime in
                self?.gameScene.update(deltaTime: deltaTime)
            },
            handleInput: { [weak self] in
                self?.gameScene.handleInput()
            }
        )
    }
}
