//
//  GameScene.swift
//  SampleProject
//
//  Generated by UntoldEngine Build System
//

import Foundation
import SamplePlugin
import simd
import UntoldComponentKit
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {
    private var wasRightMousePressed: Bool = false

    init() {
        // Configure asset paths
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // The editor saves plugins with the scene. This sample has no saved scene, so it
        // builds one in code, which also shows the code-side API.
        createSampleScene()
    }

    /// A cube that spins and bobs: both behaviours are component plugins from
    /// Sources/SampleProjectComponents, attached here exactly as the editor's Inspector does.
    private func createSampleScene() {
        let cube = createEntity()
        setEntityName(entityId: cube, name: "Sample Cube")
        setEntityMeshDirect(entityId: cube, meshes: BasicPrimitives.createCube(extent: 1.0), assetName: "sample_cube")
        translateTo(entityId: cube, position: simd_float3(0, 0, 0))

        let spinner = ScenePluginSystem.shared.add(Spinner.self, to: cube)
        spinner?.speed = 60
        ScenePluginSystem.shared.add(Bobber.self, to: cube)

        createSampleEntityKinds()

        setSceneReady(true)
    }

    /// The kinds of entity this project and its plugin add to the editor's creation shelves,
    /// made here the way the shelves make them. Each is an EntityPlugin: the entity's own
    /// properties, and whichever of geometry and editor representation it has.
    private func createSampleEntityKinds() {
        let kinds = EntityPluginRegistry.shared

        // Geometry only, from the plugin. The ring's numbers are the entity's own properties.
        if let ring = kinds.instantiate(TorusEntity.self, entityName: "Ring") {
            ring.ringRadius = 1.4
            ring.tubeRadius = 0.08
            ring.rebuild()
        }

        // Geometry and an editor representation. The game shows the tube; the control points
        // are for the editor. A sphere travels along it with a component any entity could have.
        if let path = kinds.instantiate(SplinePathEntity.self, at: simd_float3(0, 0.5, -2.5), entityName: "Path") {
            let ball = createEntity()
            setEntityName(entityId: ball, name: "Path Ball")
            setEntityMeshDirect(entityId: ball, meshes: BasicPrimitives.createSphere(extent: 0.15), assetName: "path_ball")
            ScenePluginSystem.shared.add(PathFollower.self, to: ball)?.path = EntityRef(getEntityName(entityId: path.entity))
        }

        // An editor representation only: a flag in the editor, a position in the game.
        kinds.instantiate(SpawnPointEntity.self, at: simd_float3(-2, 0, 1), entityName: "Red Spawn")?.team = .red

        // Neither: properties and behaviour. The round starts counting with play mode.
        kinds.instantiate(GameRulesEntity.self, entityName: "Rules")

        Logger.log(message: "[Sample] Red team spawns at \(SpawnPointEntity.all(for: .red))")
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        // Plugins written in code: register the component and entity plugins linked into
        // this app, then start them. Scenes loaded afterwards bind what they saved to these types.
        ScenePluginSystem.discoverInApp()
        ScenePluginSystem.install()
        ScenePluginSystem.shared.startPlayMode()
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerKeyboardEvents()
        InputSystem.shared.registerMouseEvents()
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false {
            return
        }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false {
            return
        }
        if isSceneReady() == false {
            return
        }

        let input = InputSystem.shared
        let camera = findGameCamera()

        moveCameraWithInput(
            entityId: camera,
            input: (
                w: input.keyState.wPressed,
                a: input.keyState.aPressed,
                s: input.keyState.sPressed,
                d: input.keyState.dPressed,
                q: input.keyState.qPressed,
                e: input.keyState.ePressed
            ),
            speed: 1.0,
            deltaTime: 0.1
        )

        if input.keyState.rightMousePressed {
            if !wasRightMousePressed {
                setOrbitOffset(entityId: camera, uTargetOffset: 5.0)
            }
            var dx = input.mouseDeltaX
            var dy = input.mouseDeltaY
            if abs(dx) < abs(dy) {
                dx = 0
            } else {
                dy = 0
            }
            orbitCameraAround(entityId: camera, uDelta: simd_float2(dx, dy))
        }
        wasRightMousePressed = input.keyState.rightMousePressed

        // Add your custom input handling here
    }
}
