//
//  GameScene.swift
//  SampleProject
//
//  Generated by UntoldEngine Build System
//

import Foundation
import SamplePlugin
import simd
import UntoldComponentKit
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {
    private var wasRightMousePressed: Bool = false

    init() {
        // Configure asset paths
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // The editor saves components with the scene. This sample has no saved scene, so it
        // builds one in code, which also shows the code-side API.
        createSampleScene()
    }

    /// A cube that spins and bobs: both behaviours are code components from
    /// Sources/SampleProjectComponents, attached here exactly as the editor's Inspector does.
    private func createSampleScene() {
        let cube = createEntity()
        setEntityName(entityId: cube, name: "Sample Cube")
        setEntityMeshDirect(entityId: cube, meshes: BasicPrimitives.createCube(extent: 1.0), assetName: "sample_cube")
        translateTo(entityId: cube, position: simd_float3(0, 0, 0))

        let spinner = CodeComponentSystem.shared.add(Spinner.self, to: cube)
        spinner?.speed = 60
        CodeComponentSystem.shared.add(Bobber.self, to: cube)

        createSampleEntityKinds()

        setSceneReady(true)
    }

    /// The kinds of entity this project and its plugin add to the editor's creation shelves,
    /// made here from the same templates. One of each sort:
    /// a shape of its own, an editor-only marker, and nothing to show at all.
    private func createSampleEntityKinds() {
        let templates = EntityTemplateRegistry.shared

        // From the plugin. The engine has no torus; TorusShape builds the mesh, here as in the editor.
        if let ring = templates.instantiate("TorusEntity", entityName: "Ring"),
           let shape = CodeComponentRegistry.component(TorusShape.self, on: ring)
        {
            shape.ringRadius = 1.4
            shape.tubeRadius = 0.08
            shape.rebuild()
        }

        // In the editor this one is a flag icon. In the game it is only a position to ask for.
        if let spawn = templates.instantiate("SpawnPointEntity", at: simd_float3(-2, 0, 1), entityName: "Red Spawn") {
            CodeComponentRegistry.component(SpawnPoint.self, on: spawn)?.team = .red
        }

        // Rules have no shape anywhere; the round starts counting with play mode.
        templates.instantiate("GameRulesEntity", entityName: "Rules")

        Logger.log(message: "[Sample] Red team spawns at \(SpawnPoint.all(for: .red))")
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        // Code components: register the types linked into this app, then start them.
        // Scenes loaded afterwards bind their saved components to these types.
        CodeComponentRegistry.shared.discoverInApp()
        CodeComponentSystem.install()
        CodeComponentSystem.shared.startPlayMode()
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerKeyboardEvents()
        InputSystem.shared.registerMouseEvents()
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false {
            return
        }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false {
            return
        }
        if isSceneReady() == false {
            return
        }

        let input = InputSystem.shared
        let camera = findGameCamera()

        moveCameraWithInput(
            entityId: camera,
            input: (
                w: input.keyState.wPressed,
                a: input.keyState.aPressed,
                s: input.keyState.sPressed,
                d: input.keyState.dPressed,
                q: input.keyState.qPressed,
                e: input.keyState.ePressed
            ),
            speed: 1.0,
            deltaTime: 0.1
        )

        if input.keyState.rightMousePressed {
            if !wasRightMousePressed {
                setOrbitOffset(entityId: camera, uTargetOffset: 5.0)
            }
            var dx = input.mouseDeltaX
            var dy = input.mouseDeltaY
            if abs(dx) < abs(dy) {
                dx = 0
            } else {
                dy = 0
            }
            orbitCameraAround(entityId: camera, uDelta: simd_float2(dx, dy))
        }
        wasRightMousePressed = input.keyState.rightMousePressed

        // Add your custom input handling here
    }
}
