//
//  GameScene.swift
//  SampleProject
//
//  Generated by UntoldEngine Build System
//

import Foundation
import simd
import UntoldComponentKit
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {
    private var wasRightMousePressed: Bool = false

    init() {
        // Configure asset paths
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // The editor saves components with the scene. This sample has no saved scene, so it
        // builds one in code, which also shows the code-side API.
        createSampleScene()
    }

    /// A cube that spins and bobs: both behaviours are code components from
    /// Sources/SampleProjectComponents, attached here exactly as the editor's Inspector does.
    private func createSampleScene() {
        let cube = createEntity()
        setEntityName(entityId: cube, name: "Sample Cube")
        setEntityMeshDirect(entityId: cube, meshes: BasicPrimitives.createCube(extent: 1.0), assetName: "sample_cube")
        translateTo(entityId: cube, position: simd_float3(0, 0, 0))

        let spinner = CodeComponentSystem.shared.add(Spinner.self, to: cube)
        spinner?.speed = 60
        CodeComponentSystem.shared.add(Bobber.self, to: cube)

        setSceneReady(true)
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        // Code components: register the types linked into this app, then start them.
        // Scenes loaded afterwards bind their saved components to these types.
        CodeComponentRegistry.shared.discoverInApp()
        CodeComponentSystem.install()
        CodeComponentSystem.shared.startPlayMode()
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerKeyboardEvents()
        InputSystem.shared.registerMouseEvents()
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false {
            return
        }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false {
            return
        }
        if isSceneReady() == false {
            return
        }

        let input = InputSystem.shared
        let camera = findGameCamera()

        moveCameraWithInput(
            entityId: camera,
            input: (
                w: input.keyState.wPressed,
                a: input.keyState.aPressed,
                s: input.keyState.sPressed,
                d: input.keyState.dPressed,
                q: input.keyState.qPressed,
                e: input.keyState.ePressed
            ),
            speed: 1.0,
            deltaTime: 0.1
        )

        if input.keyState.rightMousePressed {
            if !wasRightMousePressed {
                setOrbitOffset(entityId: camera, uTargetOffset: 5.0)
            }
            var dx = input.mouseDeltaX
            var dy = input.mouseDeltaY
            if abs(dx) < abs(dy) {
                dx = 0
            } else {
                dy = 0
            }
            orbitCameraAround(entityId: camera, uDelta: simd_float2(dx, dy))
        }
        wasRightMousePressed = input.keyState.rightMousePressed

        // Add your custom input handling here
    }
}
