//
//  GameSceneUtils.swift
//  SampleProject
//
//  Generated by UntoldEngine Build System
//

import Foundation
import UntoldEngine

extension GameScene {
    // MARK: - Asset Setup

    /// Configure the asset base path for the bundled GameData
    func setupAssetPaths() {
        if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
            assetBasePath = gameDataURL
            Logger.log(message: "✅ Found GameData at: \(gameDataURL.path)")
        } else if let resourceURL = Bundle.main.resourceURL {
            let gameDataPath = resourceURL.appendingPathComponent("GameData")
            if FileManager.default.fileExists(atPath: gameDataPath.path) {
                assetBasePath = gameDataPath
                Logger.log(message: "✅ Found GameData in Resources: \(gameDataPath.path)")
            } else {
                Logger.log(message: "⚠️ GameData not found. Bundle resources: \(resourceURL.path)")
            }
        }
    }
}
